name: mighty_sort_news
description: A new Flutter application created using flutter 3.3.7 & Dart SDK version 2.19.6

publish_to: 'none' #Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Other
  cupertino_icons: ^1.0.5
  nb_utils: ^5.0.6
  google_fonts: ^4.0.3
  intl: ^0.18.0
  html: ^0.15.2
  url_launcher: ^6.1.10
  share: ^2.0.4
  package_info_plus: ^3.0.3
  onesignal_flutter: ^3.5.1
  carousel_slider: ^4.2.1
  connectivity_plus_web: ^1.2.5

  #Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  firebase_crashlytics: ^3.1.0
  firebase_messaging: ^14.4.0
  paginate_firestore: ^1.0.3+1

  #SignIn
  google_sign_in: ^6.1.0
  the_apple_sign_in: ^1.1.1
  country_code_picker: ^3.0.0

  flutter_html: ^2.2.1
  cached_network_image: ^3.2.3
  flutter_vector_icons: ^2.0.0
  photo_view: ^0.14.0
  image_picker: ^0.8.7+1
  screenshot: ^1.3.0
  path_provider: ^2.0.14
  flutter_share_me: ^1.4.0
  flutter_inappwebview: ^5.7.2+3
  store_redirect: ^2.0.1
  youtube_player_flutter: ^8.1.2
  page_transition: ^2.0.9
  lottie: ^2.3.2
  file_picker: ^5.2.7
  story_view: ^0.14.0
  flutter_switch: ^0.3.2

  #VideoPlayer
  chewie: ^1.4.0
  video_player: ^2.7.0
  flick_video_player: ^0.5.0

  #Ads
  facebook_audience_network: ^1.0.1
  google_mobile_ads: ^2.4.0


  #Mobx
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  flutter_launcher_icons: any
  in_app_review: ^2.0.6

  multi_select_flutter: ^4.1.3
  pin_code_fields: ^8.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  firebase_core_platform_interface: ^4.6.0
  intl: ^0.18.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  firebase_crashlytics: ^3.1.0
  firebase_messaging: ^14.4.0
  package_info_plus: ^3.0.3
  file_picker: ^5.2.7
  ffi: ^1.1.2
  auto_size_text: ^3.0.0

  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/flags/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
